### ISSUE TITLE
Can we use dos2unix instead own implementation here

### ISSUE THREAD

**Issue by markusweigelt** [markusweigelt/ocrd_manager#11]
@bertsky https://github.com/markusweigelt/ocrd_manager/blob/668d2305525e6ad91e2b7b59891ec105d86b37af/for_production.sh#L72

**Comment by bertsky** [comment]
What do you mean dos2unix?

**Comment by markusweigelt** [comment]
I suspected here that this replacement takes place to avoid certain windows characters but it is general and has nothing to do with it. :-/

Think since the workflows are written independently of the Linux system it can come here to problems when CR LF newlines are not converted.

**Comment by bertsky** [comment]
> I think since the workflows are written independently of the linux system it can come to problems at this point when CR LF newlines are not converted.

Yes, to make this compatible with the DOS/Windows EOF convention, you need #12
