### ISSUE TITLE
Add ocrd_browser via Broadway HTTP bridge

### ISSUE THREAD

**Issue by markusweigelt** [markusweigelt/ocrd_manager#6]
The ocrd browser should be added similar to the controller.

**Comment by bertsky** [comment]
I.e. more or less the inverse of https://github.com/bertsky/ocrd_controller/commit/894008fa23853508d8c1170ff92c1fb62ab93c49

But let's not integrate this directly, but via https://github.com/markusweigelt/kitodo_production_ocrd's compose file – as a service! (The interactive part of starting up the browser for a specific path could be implemented as extra endpoint via a tiny web server on top of Broadway.)
